[Build]
WithNetwork=true

[Content]
BuildScripts=modules/example/mkosi.build
ExtraTrees=modules/example/files
           modules/example/webserver.py:/opt/example/webserver.py

Packages=libtss2-esys-3.0.2-0t64 # The attest-cli tool depends on libtss2 for Azure attestation
         libtss2-tctildr0t64
BuildPackages=cargo/trixie-backports # Required to build the attest-cli tool
              rustc/trixie-backports
              libtss2-dev
